deprecated:
  - name: npu_apply_adam
    replace: 'torch.optim.Adam or torch.optim.adam'
  - name: npu_apply_adam.out
    replace: 'torch.optim.Adam or torch.optim.adam'
  - name: npu_conv_transpose2d
    replace: 'torch.nn.functional.conv_transpose2d'
  - name: npu_conv2d
    replace: 'torch.nn.functional.conv2d'
  - name: npu_conv2d.out
    replace: 'torch.nn.functional.conv2d'
  - name: npu_convolution
    replace: 'torch.nn.functional.conv2d or torch.nn.functional.conv3d'
  - name: npu_convolution_transpose
    replace: 'torch.nn.functional.conv_transpose2d or torch.nn.functional.conv_transpose3d'
  - name: npu_gru
    replace: 'torch.nn.GRU'
  - name: npu_layer_norm_eval
    replace: 'torch.nn.functional.layer_norm or torch.optim.adam'
  - name: npu_min.dim
    replace: 'torch.min'
  - name: npu_min.names_dim
    replace: 'torch.min'
  - name: npu_mish
    replace: 'torch.nn.functional.mish'
  - name: npu_nms_rotated
  - name: npu_ptiou
    replace: 'torch_npu.npu_iou'
  - name: npu_silu
    replace: 'torch.nn.functional.silu'
  - name: npu_sort_v2
    replace: 'torch.sort'
  - name: npu_sort_v2.out
    replace: 'torch.sort'
  - name: one_
    replace: 'torch.fill_ or torch.ones_like'
  - name: npu_conv3d
    replace: 'torch.nn.functional.conv3d'
  - name: npu_conv3d.out
    replace: 'torch.nn.functional.conv3d'
  - name: npu_transpose_trans_contiguous.out
    replace: 'npu_transpose'
  - name: npu_indexing_trans_contiguous.out
    replace: 'npu_indexing'
  - name: npu_bmmV2
    replace: 'torch.bmm and torch.view'
  - name: npu_mla_prolog_v2
    replace: 'npu_mla_prolog_v3'
  - name: npu_mla_prolog
    replace: 'npu_mla_prolog_v3'
  - name: npu_alloc_float_status
  - name: npu_anchor_response_flags
  - name: npu_batch_nms
  - name: npu_bert_apply_adam
  - name: npu_bounding_box_decode
  - name: npu_bounding_box_encode
  - name: npu_ciou
  - name: npu_clear_float_status
  - name: npu_diou
  - name: npu_get_float_status
  - name: npu_giou
  - name: npu_grid_assign_positive
  - name: npu_indexing
  - name: npu_iou
  - name: npu_nms_v4
  - name: npu_nms_with_mask
  - name: npu_one_hot
  - name: npu_pad
    replace: 'torch.nn.functional.pad'
  - name: npu_ps_roi_pooling
  - name: npu_random_choice_with_mask
  - name: npu_rotated_iou
  - name: npu_rotated_overlaps
  - name: npu_sign_bits_pack
  - name: npu_sign_bits_unpack
  - name: npu_slice
    replace: 'torch.slice'
  - name: npu_softmax_cross_entropy_with_logits
  - name: npu_transpose
    replace: 'torch.permute'
  - name: npu_yolo_boxes_encode
  - name: npu_fused_attention_score
    replace: 'npu_fusion_attention'
  - name: npu_multi_head_attention
  - name: npu_dropout_with_add_softmax
  - name: dropout_with_byte_mask
